import React, { useState } from 'react';
import { Compass, ShieldCheck, HelpCircle, Sparkles, AlertOctagon, CheckCircle2 } from 'lucide-react';

const MAP_LAYERS = [
  {
    level: '01',
    stage: 'KNOWN // EMPIRICAL FACT',
    type: 'FACT',
    color: '#111111',
    description: 'Empirically validated and mathematically proven across trillions of tokens and multi-thousand GPU clusters.',
    items: [
      'Self-attention has constant O(1) path length between any two tokens in sequence length N.',
      'Training compute scales strictly as FLOPs ≈ 6 * Parameters * Training_Tokens (Kaplan & Chinchilla scaling laws).',
      'The raw attention matrix scales quadratically O(N²) in memory and compute without hardware-aware SRAM tiling (FlashAttention).',
      'Rotary Position Embeddings (RoPE) maintain relative distance invariants better than static absolute sinusoidal encodings.'
    ]
  },
  {
    level: '02',
    stage: 'ACTIVE RESEARCH // EMPIRICAL EVIDENCE',
    type: 'EVIDENCE',
    color: '#FF1E27',
    description: 'Current 2025-2026 experiments supported by reproducible public code and benchmark evaluations.',
    items: [
      'Test-time search (MCTS) over reasoning chain-of-thought traces yields super-linear accuracy gains in math and coding (OpenAI o1/o3, DeepSeek R1).',
      'Linear State Space Models (Mamba-2) can match Transformer perplexity when interleaved in hybrid ratios (e.g. 1 attention layer per 3 SSM layers).',
      'INT4 / FP4 post-training quantization preserves >98% of FP16 accuracy when outliers are retained in higher precision (AWQ, Marlin kernels).',
      'Synthetic pre-training data generated by teacher models requires strict quality and diversity filtering to prevent model collapse.'
    ]
  },
  {
    level: '03',
    stage: 'OPEN PROBLEM // UNSOLVED LIMITATION',
    type: 'UNSOLVED',
    color: '#888884',
    description: 'Core architectural bottlenecks that lack a proven, scalable mathematical solution in 2026.',
    items: [
      'Catastrophic forgetting during continuous post-pretraining on streaming non-stationary data.',
      '100% elimination of hallucinations in unconstrained, non-verifiable open-domain queries.',
      'Quadratic KV-cache memory explosion during concurrent multi-turn user serving at 100k+ sequence lengths.',
      'Guaranteed resistance against multi-step jailbreak attacks and adversarial prompt injection.'
    ]
  },
  {
    level: '04',
    stage: 'POSSIBLE DIRECTION // HYPOTHESIS',
    type: 'HYPOTHESIS',
    color: '#0284C7',
    description: 'Promising theoretical trajectories undergoing active peer-review and experimental validation.',
    items: [
      'Co-packaged silicon photonics replacing copper cables inside AI clusters to reduce interconnect power by 80%.',
      'Fully autonomous self-improving agents that write, benchmark, and deploy their own neural architecture search code.',
      'Biomolecular diffusion foundation models designing synthetic enzymes that digest environmental plastics and capture atmospheric carbon.',
      'Recurrent test-time compute networks with native execution sandboxes for verified theorem proving.'
    ]
  },
  {
    level: '05',
    stage: 'UNCERTAIN FUTURE // SPECULATION',
    type: 'SPECULATION',
    color: '#7C3AED',
    description: 'Theoretical extrapolations grounded in technological trends, but without definitive experimental proof.',
    items: [
      'Emergence of artificial general intelligence (AGI) through continuous multimodal foundation model scale alone.',
      'Quantum computing accelerators outperforming classical GPU tensor cores for non-convex neural network optimization.',
      'Direct brain-computer neural interfaces synthesizing thoughts into tokenized latent vector streams in real time.',
      'Decentralized low-power global mesh clusters training frontier models without centralized gigawatt data centers.'
    ]
  }
];

export default function FutureMap() {
  const [selectedType, setSelectedType] = useState('ALL');

  const visibleLayers = selectedType === 'ALL'
    ? MAP_LAYERS
    : MAP_LAYERS.filter(l => l.type === selectedType);

  return (
    <div className="bg-[#FAF9F5] border-2 border-[#111111] p-5 sm:p-8 shadow-[6px_6px_0px_#111111] font-mono text-[#111111] space-y-6">
      
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#C9C7C0] pb-4">
        <div>
          <span className="text-[10px] text-[#FF1E27] font-bold uppercase tracking-widest block">
            EVIDENCE-BASED TRAJECTORY MAPPING
          </span>
          <h3 className="font-syne font-extrabold text-xl sm:text-2xl uppercase tracking-tight text-[#111111]">
            Future Research Direction Map
          </h3>
        </div>

        {/* Evidence Category Filter */}
        <div className="flex items-center gap-1.5 flex-wrap text-[10px]">
          {['ALL', 'FACT', 'EVIDENCE', 'UNSOLVED', 'HYPOTHESIS', 'SPECULATION'].map(type => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`px-2 py-1 uppercase tracking-wider font-bold border transition-colors cursor-pointer ${
                selectedType === type
                  ? 'bg-[#111111] text-white border-[#111111]'
                  : 'bg-white text-stone-600 border-[#C9C7C0] hover:border-[#111111]'
              }`}
            >
              {type}
            </button>
          ))}
        </div>
      </div>

      {/* Structured 5-Tier Evidence Hierarchy */}
      <div className="space-y-4">
        {visibleLayers.map((layer) => (
          <div
            key={layer.level}
            className="p-5 bg-white border-2 border-[#111111] shadow-[3px_3px_0px_#111111] space-y-3"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-[#E4E2DC] pb-2.5">
              <div className="flex items-center gap-2.5">
                <span className="text-xs font-bold bg-[#111111] text-white px-2 py-0.5">
                  STAGE {layer.level}
                </span>
                <span className="font-syne font-bold text-sm text-[#111111] uppercase tracking-wide">
                  {layer.stage}
                </span>
              </div>

              <span className={`text-[10px] font-bold px-2 py-0.5 border ${
                layer.type === 'FACT' ? 'bg-emerald-50 text-emerald-800 border-emerald-300' :
                layer.type === 'EVIDENCE' ? 'bg-rose-50 text-[#FF1E27] border-rose-200' :
                layer.type === 'UNSOLVED' ? 'bg-amber-50 text-amber-800 border-amber-300' :
                layer.type === 'HYPOTHESIS' ? 'bg-sky-50 text-sky-800 border-sky-300' :
                'bg-purple-50 text-purple-800 border-purple-300'
              }`}>
                {layer.type} (STRICTLY LABELED)
              </span>
            </div>

            <p className="font-sans text-xs text-[#555555]">
              {layer.description}
            </p>

            {/* Bullets */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2 pt-1 text-xs">
              {layer.items.map((item, idx) => (
                <div key={idx} className="p-2.5 bg-[#FAF9F5] border border-[#C9C7C0] flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#FF1E27] mt-1.5 shrink-0" />
                  <span className="font-sans text-[#333333] leading-relaxed">{item}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

    </div>
  );
}
