import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Sigma, Calculator, Info, Check, Play, RotateCcw } from 'lucide-react';

const VARIABLES = {
  Q: {
    symbol: 'Q',
    name: 'QUERY TENSOR',
    shape: '[Batch, Heads, Seq_Len, d_k]',
    intuition: 'Represents "what this token is looking for" in other tokens across the sequence. Generated by projecting the input hidden state through matrix W_Q.',
    numerical: '[[1.2, 0.4, 0.8, -0.5], [0.1, 2.1, -0.4, 1.0], [0.9, -0.2, 1.4, 0.3]]',
    practicalEffect: 'Determines the reference perspective. If Q is for token "it", it actively probes all past Key vectors to find the most syntactically/semantically compatible antecedent.'
  },
  K: {
    symbol: 'K',
    name: 'KEY TENSOR',
    shape: '[Batch, Heads, Seq_Len, d_k]',
    intuition: 'Represents "what features this token contains or advertises". Projected through matrix W_K. Dot product with Q measures relevance.',
    numerical: '[[1.0, 0.5, 0.7, -0.2], [0.3, 1.8, -0.2, 0.9], [0.8, -0.1, 1.2, 0.4]]',
    practicalEffect: 'Acts as the addressable index. High dot product with Q indicates the token contains information critical for resolving the current token representation.'
  },
  V: {
    symbol: 'V',
    name: 'VALUE TENSOR',
    shape: '[Batch, Heads, Seq_Len, d_v]',
    intuition: 'Represents the actual semantic content or payload to be extracted if attention is allocated. Projected through matrix W_V.',
    numerical: '[[0.5, 1.2, -0.3, 0.8], [1.4, 0.2, 0.9, -0.1], [0.2, 0.8, 1.1, 0.5]]',
    practicalEffect: 'The values get linearly combined according to the softmax weights. What actually flows forward into the residual stream.'
  },
  dk: {
    symbol: '√d_k',
    name: 'SCALING FACTOR',
    shape: 'Scalar: √64 = 8 or √128 ≈ 11.31',
    intuition: 'Normalizes the variance of the dot product to 1. For large d_k, the dot product of independent random variables grows with magnitude O(d_k).',
    numerical: 'd_k = 4 => √d_k = 2.0. Divides raw scores by 2.0 before softmax.',
    practicalEffect: 'Crucial for gradient stability. Without √d_k, large dot products push softmax into regions with vanishingly small gradients (zero derivatives), arresting backpropagation.'
  }
};

export default function MathematicalDeepDive() {
  const [selectedVar, setSelectedVar] = useState('Q');
  const [activeStep, setActiveStep] = useState(0);

  const activeData = VARIABLES[selectedVar] || VARIABLES['Q'];

  const steps = [
    {
      title: '01. RAW AFFINITY MATRIX (Q · K^T)',
      desc: 'Compute pairwise dot products between query vectors and key vectors.',
      matrix: [
        [2.06, 0.51, 1.76],
        [0.67, 4.79, 0.74],
        [1.72, 0.89, 2.54]
      ],
      note: 'Notice the diagonal and high off-diagonal alignment at (1,1) = 4.79.'
    },
    {
      title: '02. SCALED AFFINITY MATRIX (Q · K^T / √d_k)',
      desc: 'Divide all elements by √d_k = 2.0 to normalize variance and prevent gradient saturation.',
      matrix: [
        [1.03, 0.26, 0.88],
        [0.34, 2.40, 0.37],
        [0.86, 0.45, 1.27]
      ],
      note: 'Values are compressed into a stable range [-3, 3] ready for softmax.'
    },
    {
      title: '03. SOFTMAX NORMALIZATION (Attention Weights)',
      desc: 'Exponentiate each row and divide by row sum. Each row sums strictly to 1.0 (valid probability distribution).',
      matrix: [
        [0.44, 0.20, 0.36],
        [0.10, 0.80, 0.10],
        [0.31, 0.21, 0.48]
      ],
      note: 'Row 1 concentrates 80% of its attention mass on Token 2!'
    },
    {
      title: '04. WEIGHTED VALUE AGGREGATION (Output = Softmax · V)',
      desc: 'Linear combination of Value vectors weighted by probability mass.',
      matrix: [
        [0.60, 0.86, 0.44, 0.51],
        [1.19, 0.36, 0.79, 0.04],
        [0.55, 0.79, 0.63, 0.47]
      ],
      note: 'Final contextualized representations in R^(3 x 4) ready for residual addition.'
    }
  ];

  return (
    <div className="border border-[#C9C7C0] bg-[#FAF9F5] p-5 sm:p-7 space-y-6 font-mono text-[#111111]">
      
      {/* Section Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#C9C7C0] pb-4">
        <div>
          <div className="flex items-center gap-2 text-[#FF1E27] text-xs font-bold uppercase tracking-widest">
            <Sigma size={14} />
            <span>16 / MATHEMATICAL DEEP DIVE & TENSOR ALGEBRA</span>
          </div>
          <h3 className="font-syne text-xl sm:text-2xl font-bold uppercase tracking-tight text-[#111111] mt-1">
            FORMAL FORMULATION & STEP-BY-STEP CALCULATION
          </h3>
        </div>
        <div className="text-[10px] text-[#666660]">
          CLICK VARIABLES TO INSPECT DERIVATION & INTUITION
        </div>
      </div>

      {/* Prominent Formal Equation Box */}
      <div className="bg-[#EDECE6] border border-[#C9C7C0] p-6 text-center space-y-4">
        <div className="text-[11px] text-[#777770] font-bold uppercase tracking-widest">
          CANONICAL EQUATION (VASWANI ET AL., 2017)
        </div>
        
        <div className="font-syne text-xl sm:text-3xl lg:text-4xl font-extrabold tracking-wide text-[#111111] flex items-center justify-center gap-2 flex-wrap select-none">
          <span>Attention(</span>
          <button
            onClick={() => setSelectedVar('Q')}
            className={`px-2 py-0.5 border cursor-pointer transition-colors ${
              selectedVar === 'Q' ? 'bg-[#FF1E27] text-white border-[#FF1E27]' : 'bg-[#FAF9F5] text-[#111111] border-[#C9C7C0] hover:border-[#111111]'
            }`}
          >
            Q
          </button>
          <span>,</span>
          <button
            onClick={() => setSelectedVar('K')}
            className={`px-2 py-0.5 border cursor-pointer transition-colors ${
              selectedVar === 'K' ? 'bg-[#FF1E27] text-white border-[#FF1E27]' : 'bg-[#FAF9F5] text-[#111111] border-[#C9C7C0] hover:border-[#111111]'
            }`}
          >
            K
          </button>
          <span>,</span>
          <button
            onClick={() => setSelectedVar('V')}
            className={`px-2 py-0.5 border cursor-pointer transition-colors ${
              selectedVar === 'V' ? 'bg-[#FF1E27] text-white border-[#FF1E27]' : 'bg-[#FAF9F5] text-[#111111] border-[#C9C7C0] hover:border-[#111111]'
            }`}
          >
            V
          </button>
          <span>) = softmax(</span>
          <span className="inline-flex flex-col items-center mx-1 align-middle text-sm sm:text-lg">
            <span>
              <button
                onClick={() => setSelectedVar('Q')}
                className={`font-bold ${selectedVar === 'Q' ? 'text-[#FF1E27]' : 'text-[#111111]'}`}
              >
                Q
              </button>
              <button
                onClick={() => setSelectedVar('K')}
                className={`font-bold ${selectedVar === 'K' ? 'text-[#FF1E27]' : 'text-[#111111]'}`}
              >
                Kᵀ
              </button>
            </span>
            <span className="w-full border-t border-[#111111]" />
            <button
              onClick={() => setSelectedVar('dk')}
              className={`font-bold text-xs sm:text-base ${selectedVar === 'dk' ? 'text-[#FF1E27]' : 'text-[#111111]'}`}
            >
              √dₖ
            </button>
          </span>
          <span>)</span>
          <button
            onClick={() => setSelectedVar('V')}
            className={`px-2 py-0.5 border cursor-pointer transition-colors ${
              selectedVar === 'V' ? 'bg-[#FF1E27] text-white border-[#FF1E27]' : 'bg-[#FAF9F5] text-[#111111] border-[#C9C7C0] hover:border-[#111111]'
            }`}
          >
            V
          </button>
        </div>
      </div>

      {/* Selected Variable Telemetry Card */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-start bg-[#F1F0EB] border border-[#C9C7C0] p-5">
        <div className="md:col-span-4 space-y-2 border-r border-[#C9C7C0] pr-4">
          <div className="text-[10px] text-[#FF1E27] font-bold uppercase tracking-wider">
            VARIABLE TELEMETRY
          </div>
          <div className="font-syne text-2xl font-bold text-[#111111] flex items-center gap-2">
            <span>{activeData.symbol}</span>
            <span className="text-xs font-mono font-normal text-[#555555]">• {activeData.name}</span>
          </div>
          <div className="text-[11px] text-[#444444] font-mono">
            SHAPE: <span className="font-bold text-[#111111]">{activeData.shape}</span>
          </div>
        </div>

        <div className="md:col-span-8 space-y-3 pl-0 md:pl-2 text-xs font-sans">
          <div className="space-y-1">
            <span className="text-[10px] font-mono font-bold text-[#777770] uppercase block">
              INTUITION & ROLE
            </span>
            <p className="text-[#333333] leading-relaxed">{activeData.intuition}</p>
          </div>

          <div className="space-y-1 pt-2 border-t border-[#C9C7C0]/60">
            <span className="text-[10px] font-mono font-bold text-[#FF1E27] uppercase block">
              PRACTICAL GRADIENT & CAPACITY EFFECT
            </span>
            <p className="text-[#333333] leading-relaxed">{activeData.practicalEffect}</p>
          </div>
        </div>
      </div>

      {/* Numerical Matrix Walkthrough (3-Token Example) */}
      <div className="border border-[#C9C7C0] bg-[#FAF9F5] p-5 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#C9C7C0] pb-3">
          <div>
            <div className="text-[10px] text-[#FF1E27] font-bold uppercase tracking-wider flex items-center gap-1.5">
              <Calculator size={12} />
              <span>NUMERICAL TENSOR STEPPER (N = 3 TOKENS, d_k = 4)</span>
            </div>
            <div className="font-syne text-base font-bold text-[#111111]">
              {steps[activeStep].title}
            </div>
          </div>

          {/* Stepper Navigation */}
          <div className="flex items-center gap-2">
            {steps.map((_, i) => (
              <button
                key={i}
                onClick={() => setActiveStep(i)}
                className={`w-7 h-7 text-xs font-mono font-bold border transition-colors cursor-pointer ${
                  activeStep === i ? 'bg-[#111111] text-white border-[#111111]' : 'bg-[#FAF9F5] text-[#111111] border-[#C9C7C0] hover:border-[#111111]'
                }`}
              >
                0{i + 1}
              </button>
            ))}
          </div>
        </div>

        <p className="text-xs font-sans text-[#444444]">
          {steps[activeStep].desc}
        </p>

        {/* Matrix Display */}
        <div className="bg-[#EDECE6] p-4 border border-[#C9C7C0] overflow-x-auto">
          <div className="inline-block min-w-full font-mono text-xs">
            <div className="text-[10px] text-[#777770] pb-1 uppercase font-bold">
              TENSOR VALUES:
            </div>
            <div className="space-y-1">
              {steps[activeStep].matrix.map((row, rIdx) => (
                <div key={rIdx} className="flex items-center gap-2">
                  <span className="text-[10px] text-[#999990] w-6">T{rIdx + 1}:</span>
                  <span className="text-[#666660]">[</span>
                  {row.map((val, cIdx) => (
                    <span
                      key={cIdx}
                      className={`px-2 py-0.5 ${
                        val >= 0.7 ? 'bg-[#FF1E27] text-white font-bold' : val >= 0.4 ? 'bg-[#111111] text-white font-bold' : 'text-[#222222]'
                      }`}
                    >
                      {val.toFixed(2)}
                    </span>
                  ))}
                  <span className="text-[#666660]">]</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="text-[11px] font-sans text-[#555555] bg-[#F1F0EB] p-2.5 border border-[#C9C7C0]">
          <span className="font-bold text-[#111111]">Observation: </span>
          {steps[activeStep].note}
        </div>
      </div>

    </div>
  );
}
